### ISSUE TITLE
Tabry only offers flag completion when cmd line ends in '-'

### ISSUE THREAD

**Issue by pfgray** [evanbattaglia/tabry#13]
Tabry doesn't offer flags for completion unless the last token starts with `-`, I've narrowed it down to this check: https://github.com/evanbattaglia/tabry/blob/master/lib/tabry/models/flags_list.rb#L21C14-L21C37, which seems intentional. Is there a special reason for this?

If I remove this check, I get flag and arg completions at the same time:
<img width="860" alt="Screen Shot 2023-07-18 at 8 45 03 PM" src="https://github.com/evanbattaglia/tabry/assets/4752550/65f6189a-99f7-4776-88f1-e50ec7208205">

**Comment by evanbattaglia** [comment]
Yes, it's intentional. I didn't want lots of flags (which are optional) crowding out the suggestions. This doesn't seem uncommon across commands -- if you type `git <tab>`, it won't show you flags, just the main commands. (Seems like you need to add two dashes before it will show you flags). I see similar behavior with 'du' and 'ls'.

If it's important to you and there's a clean way of tweaking that behavior, I'd be open to it.

**Comment by pfgray** [comment]
Nah, no worries, I was just wondering if it was some limitation of bash that we could work around for fish, thanks!
